name: 'LLM Comparison'
description: 'Performs a comparison of LLM and publishes the result as a comment in the PR.'
inputs:
  go_version:
    description: 'Go version to use.'
    required: true
    default: '1.23'
  clientid:
    description: 'Client ID for authentication.'
    required: true
  clientsecret:
    description: 'Client Secret for authentication.'
    required: true
outputs:
  review_output:
    description: 'Result of code review'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ inputs.go_version }}

    - name: Install dependencies
      run: |
        cd script 
        go mod tidy
      shell: bash

    - name: Run StackSpot Analizer
      id: run_analysis
      run: |
        cd script 
        export GO111MODULE=on
        review_output=$(go run main.go)
        echo "review_output=${review_output}" >> $GITHUB_ENV
      shell: bash
      env:
        URLCALLBACK: "https://genai-code-buddy-api.stackspot.com/v1/quick-commands/callback/"
        URLEXECUTION: "https://genai-code-buddy-api.stackspot.com/v1/quick-commands/create-execution/code-review-expert"
        URLTOKEN: "https://idm.stackspot.com/itau/oidc/oauth/token"
        CLIENTID: ${{ inputs.clientid }}
        CLIENTSECRET: ${{ inputs.clientsecret }}

    - name: Post review as PR comment
      if: ${{ env.review_output != '' }} 
      uses: thollander/actions-comment-pull-request@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REVIEW_OUTPUT: ${{ env.review_output }}
      with:
        message: |
          OLá! :wave: Aqui está o resultado da análise: ${{ env.REVIEW_OUTPUT }} 
