name: LLM Comparison

on:
  pull_request:
    types: [opened, synchronize]
permissions:
  pull-requests: write

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          fetch-depth: 2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23'  
      
    - name: Install dependencies
      run:  |
        cd script 
        go mod tidy

    - name: Run StackSpot Analizer
      id: run_analysis
      run: |
        pwd  # Exibe o diretório atual
        ls -la  # Lista todos os arquivos no diretório
        export GO111MODULE=on
        review_output=$(go run main.go)
        echo "review_output<<EOF" >> $GITHUB_ENV
        echo "$review_output" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      env:
        URLCALLBACK: "https://genai-code-buddy-api.stackspot.com/v1/quick-commands/callback/"
        URLEXECUTION: "https://genai-code-buddy-api.stackspot.com/v1/quick-commands/create-execution/code-review-github"
        URLTOKEN: "https://idm.stackspot.com/itau/oidc/oauth/token"
        CLIENTID: ${{ secrets.CLIENTID }}
        CLIENTSECRET: ${{ secrets.CLIENTSECRET }}


    - name: Post review as PR comment
      if: steps.run_analysis.outputs.review_output != ''
      uses: thollander/actions-comment-pull-request@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REVIEW_OUTPUT: ${{ env.review_output }}
      with:
        message: |
           OLá! :wave: Aqui está o resultado da análise: ${{ env.REVIEW_OUTPUT }} 
        
