name: LLM Comparison

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'  

    - name: Run StackSpot Analizer
      run: |
        review_output=$(go run script/main.go)
        echo "review_output=$review_output" >> $GITHUB_ENV 

    - name: Post review as PR comment
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REVIEW_OUTPUT: ${{ env.review_output }}
      run: |
        response=$(curl -s --fail -H "Authorization: token $GITHUB_TOKEN" \
               -X POST \
               -d "{\"body\": \"**Revisión automática de código:**\n\n${REVIEW_OUTPUT}\"}" \
               "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.number }}/comments") || {
          echo "Error: Falló la solicitud curl"
          exit 1
        }
        echo "Comentario publicado con éxito: $response"
        
