name: LLM Comparison

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          fetch-depth: 2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20'  

    - name: Run StackSpot Analizer
      run: |
        review_output=$(go run script/main.go)
        echo "review_output<<EOF" >> $GITHUB_ENV
        echo "$review_output" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Post review as PR comment
      if: success()
      uses: thollander/actions-comment-pull-request@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REVIEW_OUTPUT: ${{ env.review_output }}
      with:
        message: |
           Hello world! :wave: Aqui está o resultado da análise: ${{ env.REVIEW_OUTPUT }} 
        
